"""empty message

Revision ID: 5ae96734b390
Revises: d021c734355f
Create Date: 2025-06-20 13:55:17.758503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae96734b390'
down_revision: Union[str, None] = 'd021c734355f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill_user_association', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('skill_user_association', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill_user_association', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('skill_user_association', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
