"""empty message

Revision ID: d021c734355f
Revises: ec885709d6c1
Create Date: 2025-06-20 01:32:39.235644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd021c734355f'
down_revision: Union[str, None] = 'ec885709d6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'can_teach')
    op.drop_column('skills', 'want_learn')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('want_learn', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('skills', sa.Column('can_teach', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
